### ISSUE TITLE
Formal/exact model of sustainability vs. homophily

### ISSUE THREAD

**Issue by mt-digital** [eehh-stanford/MinMaj-Adaptation-Diffusion#1]
We currently have the attached computational, agent-based model results for our work on sustainability versus homophily. We find that an innovation is most sustainable when it is introduced to the minority group at the beginning of the simulation. Moderately high levels of homophily further optimize sustainability.
![image](https://user-images.githubusercontent.com/2425472/200409165-799c664b-3e79-4b55-aad1-8e51d79cb170.png)

In the plot above, the line and markers both represent the simulated results. However, it would be even more powerful if we could support our computational results with "exact" results obtained through formal mathematical modeling. I envision a figure with the exact solution as a smooth line and our simulations represented by markers that should follow the exact calculations. This is perhaps a reach and not necessary, but it could also significantly strengthen this model as a foundation for modeling cultural innovations and other cultural phenomena such as disease transmission.

Jamie has provided one example using non-random mixing terms following an epidemiological approach (Morris, 1991). This is promising, but I would also be interested to explore the approach reviewed by Cavalli-Sforza and Feldman (1981, p. 109 - 129), where they calculate the probability of fixation (i.e. _sustainability_) exactly for similar, but simpler, problems (eq 2.8.21 on p. 117, and eq 2.9.9 on p. 123). They write the probability of fixation for the CBA $a$ as $F(u_0)$ where $u_0$ is the initial frequency of $a$. This builds on work by Kimura 1962 and Kimura and Ohta 1969. Maruyama's (1970) follow-up paper may help us think about how to incorporate population structure in a "subdivided population." We could also think about more directly extending the Fogarty and Kandler (2020) _de novo_ model to include group structure and homophily.

**References**
Morris, M. (1991). A log-linear modeling framework for selective mixing. _Mathematical Biosciences_, 107(2), 349–377. https://doi.org/10.1016/0025-5564(91)90014-A

Cavalli-Sforza, L. L., & Feldman, M. W. (1981). _Cultural Transmission and Evolution: A Quantitative Approach._ Princeton University Press.

Kimura, M. (1962). On the probability of fixation of mutant genes in a population. _Genetics_, 47, 713–719. https://doi.org/10.1017/S0016672300001543

Kimura, M., & Ohta, T. (1969). The average number of generations until fixation of a mutant gene in a finite population. _Genetics_, 61, 763–771.

Maruyama, T. (1970). On the fixation probability of mutant genes in a subdivided population. _Genetical Research_, 15(2), 221–225. https://doi.org/10.1017/S0016672300001543

Fogarty, L., & Kandler, A. (2020). The fundamentals of cultural adaptation: implications for human adaptation. _Scientific Reports_, 10(1), 1–11. https://doi.org/10.1038/s41598-020-70475-3

**Comment by mt-digital** [comment]
Current plan: push forward with selective-mixing model (Morris, 1991), and think about how to modify agent-based model to match selective-mixing model assumptions.

I would like to continue developing the drift models I mentioned initially to add group structure, but it will take more work possibly beyond the scope of our current PTB project.

**Comment by juemos** [comment]
I can actually re-do the model using a simpler approach to parameterizing homophily. I realized that I actually have that as well. I'd need to translate from Mathematica code, but it's pretty simple (it's also possible it started out as R code and was later translated into Mathematica).

**Comment by mt-digital** [comment]
For this paper let's go with the ABM; future iterations can expand methodologies if it makes sense.
