### ISSUE TITLE
Review "Cultural evolutionary public policy" Efferson and other papers

### ISSUE THREAD

**Issue by mt-digital** [eehh-stanford/MinMaj-Adaptation-Diffusion#3]
I think we need to address a series of papers by Efferson and colleagues who have been working on interventions against female genital cutting (FGC) in Africa, especially. This would be a good opportunity for a student to review this literature and start to understand what is cultural evolution and how can it be used to design successful interventions for positive change. Below are two references to start with, one from Efferson and colleagues and a summary by Michael Muthukrishna. Please follow further references and incorporate them into the text below, and connect them to the topic of our paper. This is also related to the Bak-Coleman et al. (2021) PNAS Perspective on "Stewardship of global collective behavior" shared by Jamie on Slack. We need to say something about current approaches to such "stewardship" and how our work fits in.

Muthukrishna, M. (2020). Cultural evolutionary public policy. _Nature Human Behaviour_, 4(1), 12–13. https://doi.org/10.1038/s41562-019-0780-6

Efferson, C., Vogt, S., \& Fehr, E. (2020). The promise and the peril of using social influence to reverse harmful traditions. _Nature Human Behaviour_, 4(1), 55–68. https://doi.org/10.1038/s41562-019-0768-2

Bak-Coleman, J. B., Alfano, M., Barfuss, W., Bergstrom, C. T., Centeno, M. A., Couzin, I. D., Donges, J. F., Galesic, M., Gersick, A. S., Jacquet, J., Kao, A. B., Moran, R. E., Romanczuk, P., Rubenstein, D. I., Tombak, K. J., van Bavel, J. J., & Weber, E. U. (2021). Stewardship of global collective behavior. Proceedings of the National Academy of Sciences of the United States of America, 118(27), 1–10. https://doi.org/10.1073/pnas.2025764118

See comment under "Cultural Evolution" subsection that indicates the approximate location of this material in the paper. Perhaps the organization of the Introduction needs to be modified to include a not-only-cultural-evolution section on such efforts to guide collective behavior.

**Comment by mt-digital** [comment]
@juemos has posted the branch 3-review-cultural-evolutionary-public-policy with code to reproduce the Efferson figures (available under Development section at right). Just curious, Jamie, would you mind posting the original source of this? Did you do it all _de novo_ or did you start with some supplemental information from Efferson?

**Comment by juemos** [comment]
No, I just recreated it myself. I don’t think they included the code with their paper, but I could ask for it.

It’s probably a personality flaw, but I do this pretty regularly. I see a figure in the paper and I try to re-create it myself. The rational thing to do, of course, would be to ask for the code to create the figure, but I think that’s less fun that way.

**Comment by mt-digital** [comment]
I appreciate the code. I think the model is not quite right for our approach, which is more about group structure than cognitive heterogeneity. We should address heterogeneity in the Discussion since we will probably end up ignoring cognitive heterogeneity.
